export const COMMON_CONSTS = {
  AT_YOUR: 'AT YOUR',
  SERVICE: 'SERVICE',
  ORDER_IN_PROGRESS: 'ORDER IN PROGRESS',
  STATUS: 'STATUS',
  GUEST: 'GUEST',
  ROOM: 'ROOM',
  LOCATION: 'LOCATION',
  COMPLETED_ORDERS: 'COMPLETED ORDERS',
  SIGNED_IN_AS: 'Signed in as:',
  MARK_TAPPERT: 'Mark Tappert',
  SIGN_OUT: 'SIGN OUT',
};
